apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
spec:
  selector:
    matchLabels:
      app: login
  replicas: 2  # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: asdfn0/backend_final
        ports:
        - containerPort: 5000
