apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
spec:
  selector:
    matchLabels:
      app: video
  replicas: 2  # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: video
        image: asdfn0/spring_boot
        ports:
        - containerPort: 8080
